### ISSUE TITLE
PDF: Some text overflows the page

### ISSUE THREAD

**Issue by reinaldoarrosi** [ZSvedic/EBH-book#12]
This can be seen in page 55 of EBH-standalone.pdf. 
This is probably because the text is a multiline text inside a table.

Since this table has only one column, may it can be rewritten into a normal paragraph with 2 horizontal lines around the title.

**Comment by ZSvedic** [comment]
@reinaldoarrosi Ok, then please rewrite it to a normal paragraph, but add horizontal lines before title, after title, and after the job ad end. Seems that markdown has [horizontal line syntax](https://www.markdownguide.org/basic-syntax/#horizontal-rules), so we can use that instead of single column table.
