### ISSUE TITLE
EBH-standalone.pdf: Cover image as first page

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#8]
EBH-standalone.pdf: Cover image as first page (same as EPUB). Unfortunately, it seems that cover-image doesn't do anyhting: https://github.com/rstudio/bookdown/issues/473

**Comment by ZSvedic** [comment]
I couldn't do this, I got some pandoc error: https://stackoverflow.com/questions/25591517/pandoc-inserting-pages-before-generated-table-of-contents

**Comment by reinaldoarrosi** [comment]
I've created 2 different LaTeX templates (pdf-print-front-template.tex and pdf-standalone-front-template.tex) and changed md2all.bat to use these templates when generating print/standalone PDFs

I've modified pdf-standalone-front-template.tex so that it adds the cover-image as the first page of the PDF file.
