### ISSUE TITLE
EPUB and PDF: Reduce file sizes

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#9]

**Comment by ZSvedic** [comment]
For some reason, EPUB and PDF sizes are 30-40 times larger than HTML file:
![image](https://user-images.githubusercontent.com/43754593/72626945-effeb900-394b-11ea-9952-a8fd8da5eda5.png)

**Comment by reinaldoarrosi** [comment]
Regarding EPUB size, this is because EPUB includes images within the file itself (it's just a zip file) and HTML references images from "../images", that's why their sizes are so different.

PDF files also include images, but their size is considerably larger than EPUB. I'll need to investigate it further.
